### PR TITLE
Migrate digital-subscription-authorisation from TC to GHA

### PR DESCRIPTION
**Pull request by shtukas**
Migrate digital-subscription-authorisation from TC to GHA

### CODE REVIEW

**Comment by shtukas** [comment]
Screenshot 2023-10-12 at 14 10 28

**Comment by shtukas** [comment]
Screenshot 2023-10-12 at 14 11 54

**Comment by shtukas** [comment]
Screenshot 2023-10-12 at 14 12 02

**Comment by shtukas** [comment]
PROD:

PROD


CODE:

CODE

**Review by paulbrown1982 — APPROVED** [review]
👍 LGTM

**Pull request merged**
